### ISSUE TITLE
thank you man

### ISSUE THREAD

**Issue by yjavaherian** [gurvancampion/nuxt-electron-trpc-prisma#1]
god bless you man.
this line saved me; I've wasted a day on this bug 🥲. did you came up with the fix or found it somewhere else?
``` ts
 // Force to have the .prisma folder with pnpm
  output="../../node_modules/.prisma/client"
```

**Comment by gurvancampion** [comment]
I found this solution on Prisma issues if I remember correctly, you could otherwise specify another path and make sure to modify the one in `electron-builder` as well
